### ISSUE TITLE
Question bunnyhop

### ISSUE THREAD

**Issue by Septembers** [Javierko/DeathrunCSGO#2]
In the updated game mode, everything is fine.
I have a 128 tickrate server, it's not smooth. Watch the video, what can you do?

https://youtu.be/zaVXXEWd5nQ

**Comment by Javierko** [comment]
I don't think this is caused by plugin.
Try these cvars:
```
sv_accelerate 5.5 
sv_airaccelerate 100
sv_maxvelocity 4000  
sv_accelerate_use_weapon_speed 0
sv_staminalandcost 0 
sv_staminajumpcost 0 
sv_staminamax 0 
sv_staminajumpcost 0 
sv_gravity 800 
sv_friction 5.2
sv_enablebunnyhopping 1 
```

**Comment by Septembers** [comment]
> I don't think this is caused by plugin.
> Try these cvars:
> 
> ```
> sv_accelerate 5.5 
> sv_airaccelerate 100
> sv_maxvelocity 4000  
> sv_accelerate_use_weapon_speed 0
> sv_staminalandcost 0 
> sv_staminajumpcost 0 
> sv_staminamax 0 
> sv_staminajumpcost 0 
> sv_gravity 800 
> sv_friction 5.2
> sv_enablebunnyhopping 1 
> ```

It seems to be better. There is still a suggestion. Can add cvar enable / disable autorespawn

**Comment by Septembers** [comment]
liked your plugin

**Comment by Javierko** [comment]
> Can add cvar enable / disable autorespawn

I made cvar to enable or disable auto respawn, cvar **sm_deathrun_respawn** (default value 1)

If is respawn enabled you can customize your VIP or Non-VIP players life with cvars:
For Non-VIP: **sm_deathrun_lifes_novip** (default value 1)
For VIP: **sm_deathrun_lifes_vip** (default value 3)

**Comment by Septembers** [comment]
> > Can add cvar enable / disable autorespawn
> 
> I made cvar to enable or disable auto respawn, cvar **sm_deathrun_respawn** (default value 1)
> 
> If is respawn enabled you can customize your VIP or Non-VIP players life with cvars:
> For Non-VIP: **sm_deathrun_lifes_novip** (default value 1)
> For VIP: **sm_deathrun_lifes_vip** (default value 3)

I will ask you another question
http://prntscr.com/mrjo8k

problem with compiling a plugin. what am I doing wrong?

**Comment by Javierko** [comment]
You need to have in your "include" folder this include:
http://leteckaposta.cz/163362956

e.Javierko: added in download files

**Comment by Septembers** [comment]
> You need to have in your "include" folder this include:
> http://leteckaposta.cz/163362956
> 
> e.Javierko: added in download files

strange but not helpful

**Comment by Javierko** [comment]
You're probably doing something wrong.
In include is everything what you need: [colors.inc](https://github.com/Javierko/DeathrunCSGO/blob/master/GameServer/csgo/addons/sourcemod/scripting/include/colors.inc#L98-L118)

**Comment by Septembers** [comment]
> You're probably doing something wrong.
> In include is everything what you need: [colors.inc](https://github.com/Javierko/DeathrunCSGO/blob/master/GameServer/csgo/addons/sourcemod/scripting/include/colors.inc#L98-L118)

I added one plugin, there was confusion with included. I rebuilt all my included, everything was fine. Excuse me)

Thank you for supporting the plugin. About new ideas I will write to you)

**Comment by Septembers** [comment]
> You're probably doing something wrong.
> In include is everything what you need: [colors.inc](https://github.com/Javierko/DeathrunCSGO/blob/master/GameServer/csgo/addons/sourcemod/scripting/include/colors.inc#L98-L118)

Players are asked to save their abilities so that they do not select again each round. What do you think about this?

sry my eng

**Comment by Javierko** [comment]
Added in [2.0.4](https://github.com/Javierko/DeathrunCSGO/commit/1d2b53dbefc3aa66d6f67247de30f0b291b3bbf3) something like that.

**Comment by Septembers** [comment]
I became a terrorist, but
[SM] You need to be Joker for this command!
Mr.September ^^ : !joker
Mr.September ^^ : !b
[SM] You need to be Batman for this command!
Mr.September ^^ : !batman

although other players are fine

**Comment by Septembers** [comment]
UPD: change map and 

[SM] You need to be Batman for this command!
Mr.September ^^ : !batman
[SM] You need to be Joker for this command!
Mr.September ^^ : !joker

commands do not work, although for another person everything works. there is nothing in the logs

**Comment by Javierko** [comment]
Command /joker works only for player that is chose at round start, not for another players in Terrorists.
Command /batman works only for players that are in Counter-Terrorists team.

**Comment by Septembers** [comment]
> Command /joker works only for player that is chose at round start, not for another players in Terrorists.
> Command /batman works only for players that are in Counter-Terrorists team.

At the beginning of the round and the command does not work ... the menu also does not appear. I'll check it tomorrow, sleep now.

for CT everything is ok with me

**Comment by Javierko** [comment]
I'm going to solve that problem in [this](https://github.com/Javierko/DeathrunCSGO/issues/3) issue.
