### ISSUE TITLE
Question about bhop

### ISSUE THREAD

**Issue by Septembers** [Javierko/DeathrunCSGO#4]
Anyway intermittent, bad bhop on the server.
If you use the plugin inifinite-jumping, then everything is fine, but then the double jump does not work. Maybe we will think up something?

**Comment by Javierko** [comment]
Probably bad game settings.

**Comment by Septembers** [comment]
> Probably bad game settings.

so all players

**Comment by Javierko** [comment]
On my server i don't have any problems with bhop.

**Comment by Javierko** [comment]
Can you give me your server IP?

**Comment by Javierko** [comment]
Non-Active....
