### ISSUE TITLE
Joker abilities

### ISSUE THREAD

**Issue by m1000rr** [Javierko/DeathrunCSGO#5]
So joker has two options [speed] and [bhop] .  However if I choose [speed] he is left with bhop as well which is giving him kind a speeding bhop. Is it possible to make that when you choose [speed] he would loose bhop?

**Comment by Javierko** [comment]
Added in [this version](https://github.com/Javierko/DeathrunCSGO/commit/b6a599604bc8ad79f5a481fd2457c5e773838093).

**Comment by m1000rr** [comment]
Works good now. Thanks.
