### ISSUE TITLE
a few errors 

### ISSUE THREAD

**Issue by m1000rr** [Javierko/DeathrunCSGO#6]
> L 03/12/2019 - 20:54:11: SourceMod error session started
L 03/12/2019 - 20:54:11: Info (map "workshop/368596247/deathrun_classic") (file "errors_20190312.log")
L 03/12/2019 - 20:54:11: [SM] Exception reported: Client index 2 is invalid (arg 5)
L 03/12/2019 - 20:54:11: [SM] Blaming: Deathrun.smx
L 03/12/2019 - 20:54:11: [SM] Call stack trace:
L 03/12/2019 - 20:54:11: [SM]   [0] PrintToChat
L 03/12/2019 - 20:54:11: [SM]   [1] Line 22, deathrun/runcmd.sp::OnPlayerRunCmd
L 03/12/2019 - 20:57:10: [SM] Exception reported: Client index 2 is invalid (arg 5)
L 03/12/2019 - 20:57:10: [SM] Blaming: Deathrun.smx
L 03/12/2019 - 20:57:10: [SM] Call stack trace:
L 03/12/2019 - 20:57:10: [SM]   [0] PrintToChat
L 03/12/2019 - 20:57:10: [SM]   [1] Line 22, deathrun/runcmd.sp::OnPlayerRunCmd
L 03/12/2019 - 21:10:39: Error log file session closed.

And one more little thing :  https://prnt.sc/mwz31z
And another thing, maybe also related to the errors. Sometimes ct(batman) gets spawned at T's(joker)

**Comment by m1000rr** [comment]
Any updates ?

**Comment by Javierko** [comment]
I'm sorry for that very long waiting time, but I was really busy with my work and school.

Here is [update](https://github.com/Javierko/DeathrunCSGO/commit/6db127c015e646f9b3c2a0ab72c8fd522a82522c).

But I don't understand this: 
> Sometimes ct(batman) gets spawned at T's(joker)

**Comment by m1000rr** [comment]
It is literaly as I said. Sometimes CT's gets spawned at  T's side.  Well let's say there are 20 spawn points in a map at CT side and 2 spawn points at T side. What is happening that sometimes CT( batman) gets spawned together with T(joker) . Kind of weird, because I even checked with spawntools and it looks that spawn points are right. I'll try the new version now.

**Comment by Javierko** [comment]
Works after using new version?

**Comment by Javierko** [comment]
Closed for inactivity...

**Comment by m1000rr** [comment]
> Closed for inactivity...

Sorry, for late reply wast trying to run some extended tests. There are no errors though
