### ISSUE TITLE
Adding other player models.

### ISSUE THREAD

**Issue by deivius1** [Javierko/DeathrunCSGO#7]
Hey. Is it possible to add other player models to the plugin so players on the server could have more diversity/variety? If so, how is it done? Thanks in advance.

**Comment by Javierko** [comment]
Hi,
possible, but it should take many time with making keyvalues with models and other.. Also if you want this option you can add me on [Steam](https://steamcommunity.com/id/javierkoo21/). I can do simplified version for you.
